sudo: required

dist: xenial

os:
  - linux

language: python

addons:
  apt:
    packages:
      - mesa-libGL-devel
  
matrix:
  include:
    - python: 2.7
      env: PROVIDER="conda"
    - python: 2.7
      env: PROVIDER="pypi"
    - python: 3.6
      env: PROVIDER="conda"
    - python: 3.6
      env: PROVIDER="pypi"
    - python: 3.7
      env: PROVIDER="conda"
    - python: 3.7
      env: PROVIDER="pypi"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda

install:
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test
  - conda install --yes numpy matplotlib pip
  # Download from chosen provider
  - |
    if [[ $PROVIDER == "pypi" ]]; then
      pip install --upgrade vtki
    fi
  - |
    if [[ $PROVIDER == "conda" ]]; then
      conda config --add channels conda-forge
      conda install --yes vtki
    fi

script:
  - python -c "import vtk; print(vtk.VTK_VERSION)"
  - python -c "import vtki; print(vtki.__version__)"
  - python -c "from vtki import examples; examples.load_globe()"


notifications:
  email: false
