# AppVeyor.com is a Continuous Integration service to build and run tests under Windows

build: off

environment:
  matrix:
    # incompatible with windows python 2.7
    # this is because vtk-v8.x.x requres c++11 which is incompatible
    # - PYTHON_VERSION: 2.7
    #   CONDA: C:\Miniconda

    - PYTHON_VERSION: 3.6
      CONDA: C:\Miniconda36
      PROVIDER: "pypi"

    # - PYTHON_VERSION: 3.6
    #   CONDA: C:\Miniconda36
    #   PROVIDER: "conda"

image: Visual Studio 2015

platform:
- x64

init:
  - ps: if ($Env:PLATFORM -eq "x64") { $Env:CONDA = "${Env:CONDA}-x64" }
  - ps: Write-Host $Env:PYTHON_VERSION
  - ps: Write-Host $Env:CONDA
  - ps: Write-Host $Env:PLATFORM

install:
  # Use gl-ci-helpers to set up headless display
  - "git clone --depth 1 git://github.com/pyvista/gl-ci-helpers.git"
  - "powershell gl-ci-helpers/appveyor/install_opengl.ps1"
  - "SET PYVISTA_OFF_SCREEN=True"
  # Load the conda root environment, configure and install some packages
  - '"%CONDA%\Scripts\activate.bat"'
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  # Upgrade pip
  - python -m pip install --upgrade pip
  # Install extra channel
  - conda config --add channels conda-forge
  # Handle VTK if archetecture requires conda, else let setup.py install via pip
  - conda install numpy matplotlib
  - cmd: if "%PROVIDER%" == "conda" (conda install pyvista) else (python -m pip install pyvista)

test_script:
  - python -c "import vtk; print(vtk.VTK_VERSION)"
  - python -c "import pyvista; print(pyvista.__version__)"
  - python -c "from pyvista import examples; examples.load_globe()"
  - python -c "from pyvista import examples; examples.load_uniform().plot()"
